# Generated by Django 4.2.8 on 2024-01-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='isim',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='profil',
            name='last_name',
            field=models.CharField(default='empty', max_length=30),
        ),
    ]
