# Generated by Django 4.2.8 on 2024-01-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restoranadi', models.CharField(max_length=10000)),
                ('puan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Yemek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yemekadi', models.CharField(max_length=100)),
                ('restoran', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='restoran', to='ysapp.restoran')),
            ],
        ),
    ]
