# Generated by Django 4.2.8 on 2024-01-11 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ysapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restoran',
            name='puan',
        ),
        migrations.AddField(
            model_name='restoran',
            name='kullanici',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restoran',
            name='resim',
            field=models.ImageField(null=True, upload_to='restoran_images'),
        ),
        migrations.AddField(
            model_name='yemek',
            name='kullaniciadi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='yemek',
            name='yemekadi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
