# Generated by Django 4.2.8 on 2024-01-12 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ysapp', '0002_remove_restoran_puan_restoran_kullanici_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yemek',
            name='restoran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='yemek', to='ysapp.restoran'),
        ),
    ]
