# Generated by Django 4.2.8 on 2024-01-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ysapp', '0003_alter_yemek_restoran'),
    ]

    operations = [
        migrations.AddField(
            model_name='yemek',
            name='resim',
            field=models.ImageField(null=True, upload_to='yemek_images'),
        ),
    ]
