# Generated by Django 4.2.8 on 2024-01-12 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ysapp', '0004_yemek_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yemek',
            name='restoran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yemek', to='ysapp.restoran'),
        ),
    ]
